### ISSUE TITLE
Where is the data generation？

### ISSUE THREAD

**Issue by wsc22222** [stnoah1/infogcn#3]
Where is the data generation？

**Comment by starrycos** [comment]
I hope you can provide the code of data preprocessing for NTU dataset, which is convenient for us to reproduce the final result. Thank you for your excellent work again.

**Comment by stnoah1** [comment]
Hello,

Thank you for letting me know. I omitted the data generation code by mistake.
Please check the most recent commit, I have included data generation code.
Please let me know if you have any other questions.
