### ISSUE TITLE
Loss calculation

### ISSUE THREAD

**Issue by cheneeheng** [stnoah1/infogcn#4]
Hi there,

I have a question about the loss calculation in the following code snippet. 

https://github.com/stnoah1/infogcn/blob/7ce284b060b066c2465d70e61c2aeaa1825545a4/loss.py#L70-L75

`nmd_loss` refers to Eq 9 in the paper, and (I assume) 'l2_z_mean' refers to Eq 8 in the paper. Why is z prior (mu r) not included in the calculation for 'l2_z_mean' as per Eq 8? ~~Do you assume that the distribution of r (z_prior in the model which gets updated) has 0 mean?~~ In the paper it is assumed to be zero to make Lmmmd behave as a regularizer. Did you experiment using z_prior instead of setting it to 0 ?

great work btw.

Thanks!

**Comment by mh-ha** [comment]
Thank you for your interest in our research. 

We set the mean of z_prior to be zero with our own intuition of the geometry of latent space. The empirical Bayes approach, tuning the prior, is beyond the scope of our experiment so we haven't considered it. I hope this answers your question.

**Comment by cheneeheng** [comment]
Hi @mh-ha , 

ok got it. Thanks for the swift reply!
