### ISSUE TITLE
How to train ucla?

### ISSUE THREAD

**Issue by ch1998** [stnoah1/infogcn#5]
I use this commod "python main_ucla.py --half=True --batch_size=32 --test_batch_size=64 --step 90 100 --num_epoch=110 --n_heads=3 --num_worker=4 --k=1 --dataset=ucla --num_class=10 --lambda_1=1e-4 --lambda_2=1e-1 --z_prior_gain=3 --use_vel=False --datacase=ucla --weight_decay=0.0005 --num_person=1 --num_point=20 --graph=graph.ucla.Graph --feeder=feeders.feeder_ucla.Feeder " to train ucla dataset .
But the accuracy did not increase during training.
The following problems also occur
![捕获](https://user-images.githubusercontent.com/37291486/183356004-ed56fd74-8bab-438c-9931-61336dccc4bc.PNG)

how can I fix this problem?

**Comment by stnoah1** [comment]
Hello, it seems like the error occurred by Apex.
Please check the issue in the Apex library at the following link.
https://github.com/NVIDIA/apex/issues/26

**Comment by ch1998** [comment]
> Hello, it seems like the error occurred by Apex. Please check the issue in the Apex library at the following link. [NVIDIA/apex#26](https://github.com/NVIDIA/apex/issues/26)
![ucla](https://user-images.githubusercontent.com/37291486/183827726-2e6e6f81-bf8c-4aff-abef-0c0df32cb328.PNG)
When training ucla, it will keep skp step, resulting in too small loss scale, and finally will cause ZeroDivisionError: float division by zero, I have not changed the code, how can I avoid this error?

At the same time, because of the excessive skip steps, the accuracy of ucla did not increase at all during the previous training process.
![ucla_log](https://user-images.githubusercontent.com/37291486/183828477-a8b88896-a5f5-482b-a7d5-75b348702e45.PNG)

**Comment by ch1998** [comment]
> Hello, it seems like the error occurred by Apex. Please check the issue in the Apex library at the following link. [NVIDIA/apex#26](https://github.com/NVIDIA/apex/issues/26)

I checked the loss output and found that the loss quickly became NAN, which made the model unable to iterate. How can I fix the model
![ucla_nan](https://user-images.githubusercontent.com/37291486/183829689-f790fe24-2e17-4140-80db-586e9da8bc0b.PNG)
?

**Comment by sgchi** [comment]
Hi,
Thank you for your interest in our paper.
I guess --lambda_1=1e-1 --lambda_2=1e-1 --base_lr 0.05 --weight_decay=4e-4 might work in your case.

FYI. Hyperparameter setting details in our [supplementary materials](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Chi_InfoGCN_Representation_Learning_CVPR_2022_supplemental.pdf).

Thanks.

**Comment by ch1998** [comment]
> Hi, Thank you for your interest in our paper. I guess --lambda_1=1e-1 --lambda_2=1e-1 --base_lr 0.05 --weight_decay=4e-4 might work in your case.
> 
> FYI. Hyperparameter setting details in our [supplementary materials](https://openaccess.thecvf.com/content/CVPR2022/supplemental/Chi_InfoGCN_Representation_Learning_CVPR_2022_supplemental.pdf).
> 
> Thanks.

thank you for your reply！
I will try it.
great work btw.
