### ISSUE TITLE
Cannot reproduce the reported results on NTU60 under the cross-subject setting.

### ISSUE THREAD

**Issue by OliverHxh** [stnoah1/infogcn#6]
Hi, authors.
   Thanks for your great work and the amazing released code.  
   I try to reproduce the reported results on NTU60 under cross-subject setting using the command provided in the README. 
I train the model on NTU60 for **joint stream** by:
```
python main.py --half=True --batch_size=128 --test_batch_size=128 \
    --step 90 100 --num_epoch=110 --n_heads=3 --num_worker=4 --k=8 \
    --dataset=ntu --num_class=60 --lambda_1=1e-4 --lambda_2=1e-1 --z_prior_gain=3 \
    --use_vel=False --datacase=NTU60_CS --weight_decay=0.0005 \
    --num_person=2 --num_point=25 --graph=graph.ntu_rgb_d.Graph --feeder=feeders.feeder_ntu.Feeder
```
I train the model on NTU60 for **joint-motion stream** by:
```
python main.py --half=True --batch_size=128 --test_batch_size=128 \
    --step 90 100 --num_epoch=110 --n_heads=3 --num_worker=4 --k=8 \
    --dataset=ntu --num_class=60 --lambda_1=1e-4 --lambda_2=1e-1 --z_prior_gain=3 \
    --use_vel=False --datacase=NTU60_CS --weight_decay=0.0005 \
    --num_person=2 --num_point=25 --graph=graph.ntu_rgb_d.Graph --feeder=feeders.feeder_ntu.Feeder\
    --use_vel=True
```
And I set ```k=1``` and ```k=2``` in the above commands to get the results of the other 4 streams.
However, when I ensemble the 6 streams, I find the accuracy attains 92.7%, which is 0.3% lower than the results reported in the paper. And if I use the classical 4-stream ensemble protocol, I find the reproduced accuracy (92.3%) is still lower than the reported accuracy in the supplementary material (92.7%).
So, do I make some mistakes in reproducing the results? Or, do I miss some important details? 
Look forward to your reply. Thanks！

**Comment by stnoah1** [comment]
Hello,

In my experience, worse single-stream models sometimes actually give better ensemble results, as observed by MSG3D (https://github.com/kenziyuliu/MS-G3D/issues/25).

Or sometimes, Apex might decrease the performance. Please try half=False setup.

Thank you.
