### ISSUE TITLE
Model cannot be trained on NTU120 under cross-set setting.

### ISSUE THREAD

**Issue by OliverHxh** [stnoah1/infogcn#7]
I use the command below to train a model on NTU120 under the cross-set setting.
```
python main.py --half=True --batch_size=256 --test_batch_size=128 \
    --step 90 100 --num_epoch=110 --n_heads=3 --num_worker=4 --k=8 \
    --dataset=ntu120 --num_class=120 --lambda_1=1e-4 --lambda_2=1e-1 --z_prior_gain=3 \
    --use_vel=False --datacase=NTU120_CSet --weight_decay=0.0005 \
    --num_person=2 --num_point=25 --graph=graph.ntu_rgb_d.Graph --feeder=feeders.feeder_ntu.Feeder \
    --work_dir=results/ntu_NTU120_CSet_joint/ --amp_opt_level=1
```
However, the test accuracy is always 0.83% though the training process goes on. 
How to fix it? Thank you!

**Comment by stnoah1** [comment]
Hello,

Invalid data in the training set cause the error.
I add the code that ignores invalid data containing NaN values to the data loader.
Please pull the recent commit.

Thank you
