### ISSUE TITLE
About NTU60-sub, NTU60-view and NTU120-sub, NTU120-set

### ISSUE THREAD

**Issue by HaleYan** [stnoah1/infogcn#8]
Thank you for your great work！
I would like to know how to set in the configuration file to get the results of NTU60-sub, NTU60-view and NTU120-sub, NTU120-set dataset, and the parameter settings between NTU60-sub and NTU60-view What are the differences, and what are the differences in parameter settings between NTU120-sub and NTU120-set.

**Comment by stnoah1** [comment]
Hello, I use the command below to train our model,

```bash
python main.py --half=True --batch_size=128 --test_batch_size=128 \
    --step 90 100 --num_epoch=110 --n_heads=3 --num_worker=4 --k=1 \
    --dataset=ntu --num_class=60 --lambda_1=1e-4 --lambda_2=1e-1 --z_prior_gain=3 \
    --use_vel=False --datacase=NTU60_CS --weight_decay=0.0005 \
    --num_person=2 --num_point=25 --graph=graph.ntu_rgb_d.Graph --feeder=feeders.feeder_ntu.Feeder
```

Just change `datacase` and `dataset` to what you want to train. For NTU120 datasets, `batch_size` 256 was used.

Thank you.

**Comment by HaleYan** [comment]
Thanks for your reply!
What I want to ask is that the NTU 120 dataset has two forms, NTU120-Sub and NTU120-Set, how is your model trained on NTU120-Sub and NTU120-Set.

**Comment by stnoah1** [comment]
Please set `dataset=ntu120` and `datacase=CSet or CSub` for NTU 120 datasets. Other parameters are the same as above except `batch_size=256`.
